### ISSUE TITLE
Ability to set user account password strength standards & requirements

### ISSUE THREAD

**Issue by manda-ikaink** [fusioncms/fusioncms#155]
What is the issue?
------------------
Would like the ability to dictate user account password strength standards through the CMS.

Any other comments?
-------------------
Example from BigCommerce 
<img width="851" alt="Screen Shot 2019-12-04 at 12 47 33 PM" src="https://user-images.githubusercontent.com/5963302/70180340-a9534900-1694-11ea-9122-5f9216a66d57.png">

**Comment by skrolikowski** [comment]
[https://laravel.com/docs/6.x/validation#custom-validation-rules](Suggested implementation), which can hook into the System Settings
