### ISSUE TITLE
Feature request: Localization

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#320]
### Is your feature request related to a problem? Please describe.
There's only one language for FusionCMS: English.

### Describe the solution you'd like
Ability for users to contribute multiple languages for their content.

### Additional context
Language support is provided by Laravel, however this is for simple messaging:
https://laravel.com/docs/6.x/localization

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by Mu9tafa-Online** [comment]
**+1** for this.

**Comment by manda-ikaink** [comment]
In a pinch, I was able to follow this tutorial to add basic localization to Laravel to support multi-language on a **theme** specific level. Language files were added to the theme's `lang` directory and could be switched successfully. Doesn't account for content though. 

https://dev.to/fadilxcoder/adding-multi-language-functionality-in-a-website-developed-in-laravel-4ech
