### ISSUE TITLE
Unable to scroll after closing Modal

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#343]
### Describe the issue
Closing a Modal in an untraditional way (clicking outside of it) will cause scrolling to disable.
This appears to happen for the Field-Fieldset modals.

### To reproduce
- Edit a Field within a Fieldset (opening the Modal).
- Click the X or outside the modal to close it.
- Attempt to scroll.

### Version and browser
Version: v6.0.0 Beta 3
Browser and version: Chrome 79

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by thekanbo** [comment]
@skrolikowski What interfaces are you experiencing this on? I've tried in an entry edit page and a fieldset edit page, but am not able to recreate.

**Comment by skrolikowski** [comment]
Closing. Must have been a glitch in the Matrix.
