### ISSUE TITLE
Asset fieldtype search shows all files regardless of set root directory

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#350]
### Describe the issue
When setting the specific root directory within an asset fieldtype and _searching_ for a file, the search is preformed across all files rather than limited to the assigned root directory and its subdirectories.

### To reproduce
1. Create a fieldset
2. Add an asset fieldtype
3. Assign the root to a subdirectory
4. Attempt to search when selecting a file - you'll be presented with a collection of files from the entire file manager

### Expected behavior
The search to only be performed from the assigned root directory and upwards.

### Screenshots
![Screen Shot 2020-02-13 at 4 17 03 PM](https://user-images.githubusercontent.com/355659/74490089-4c39f780-4e7c-11ea-83f1-28fe409c576b.png)
(the above files are outside of the assigned `Blog` directory)

### Version and browser
Version: FusionCMS v6.0.0 master

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by skrolikowski** [comment]
Wasn't able to reproduce this one locally. 🤔

**Comment by kaidesu** [comment]
Correction, its not with the search.

If you click the breadcrumb, the breacrumbs update, showing the root folders, allowing you to click back through the breadcrumb and select files from any directory.
