### ISSUE TITLE
Feature request: close modal on (x) button only!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [fusioncms/fusioncms#404]
### Is your feature request related to a problem? Please describe.
It's annoying when using modal to create stuff and when clicking on browser scrollbar it closes the modal every time.

![ffff](https://user-images.githubusercontent.com/5323832/75602072-7b7e7480-5aca-11ea-990a-5bb80d24c43e.PNG)

### Describe the solution you'd like
Close the modal only when clicking the close button, not the browser scrollbar.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
What browser are you using?

**Comment by Mu9tafa-Online** [comment]
> What browser are you using?

Opera (Latest) / Microsoft Edge (Latest)
