### ISSUE TITLE
Feature request: Ability for addons to register settings

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#406]
### Is your feature request related to a problem? Please describe.
Addons should be able to easily extend and add their own CMS-level settings.

### Describe the solution you'd like
The ability to register settings through a service provider.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by skrolikowski** [comment]
See [PR#330](https://github.com/fusioncms/cms/pull/330).
