### ISSUE TITLE
Issues with PHP keywords.

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#439]
### Describe the issue
Some features of the CMS depend on user-entered content, for example, the generation of Model files based on user-entered `handle` fields. This has been found to cause unexpected issues.

### To reproduce
- Create a new Form, calling it "Default".
- Hit Save to receive an error (see screenshot below)

### Suggestions
- Need to figure out a method of detecting PHP keywords.
- Altering how all Model class names are resolved.

### Screenshots
<img width="996" alt="Screen Shot 2020-03-24 at 1 58 25 PM" src="https://user-images.githubusercontent.com/8143970/77476625-220f1a00-6dd8-11ea-8a7e-3bfb4020f723.png">

### Version and browser
Version: Latest

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
New rule class :+1: `NotReservedKeyword`
