### ISSUE TITLE
Feature request: Multi-Factor (2FA) Authentication 

### ISSUE THREAD

**Issue by cam-vanorman** [fusioncms/fusioncms#448]
### Describe the solution you'd like
Multi-Factor or 2 Factor Authentication enabled login would provide enhanced security for organizations and developers using the FusionCMS platform. This solution would provide a means for individual users to enable 2FA authentication to better secure their user login. An additional option could be introduced as a system setting to enforce 2FA for all users with access to the control panel.

The solution looks like this:
1. If the User has set up Two Factor Authentication, it will be prompted for a 2FA Code, otherwise authentication will proceed as normal.
2. If the Login attempt contains a `2fa_code` with the 2FA Code inside the Request, it will be used to check if it's valid and proceed as normal.

If a user does not have an authenticator app and can only use SMS/Email, there may be a way to hook into Laravel Notifications to enable sending via Email or SMS. To enable SMS, you would need to signup for a 3rd-party service like Nexmo/Vonage or Twillio/SendGrid.

### Describe alternatives you've considered
Other alternatives would be using a user-chosen pin or security question but both are not considered best practice in NIST guidelines for [Multi-Factor Authentication](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf):

> - Something you know may be disclosed to an attacker. The attacker might guess a
memorized secret. Where the authenticator is a shared secret, the attacker could gain
access to the CSP or verifier and obtain the secret value or perform a dictionary attack on
a hash of that value. An attacker may observe the entry of a PIN or passcode, find a
written record or journal entry of a PIN or passcode, or may install malicious software
(e.g., a keyboard logger) to capture the secret. Additionally, an attacker may determine
the secret through offline attacks on a password database maintained by the verifier.
> - Something you have may be lost, damaged, stolen from the owner, or cloned by an
attacker. For example, an attacker who gains access to the owner’s computer might copy
a software authenticator. A hardware authenticator might be stolen, tampered with, or
duplicated. Out-of-band secrets may be intercepted by an attacker and used to
authenticate their own session.
> - Something you are may be replicated. For example, an attacker may obtain a copy of the
subscriber’s fingerprint and construct a replica.

### Additional context
There's a Laravel Package, [Laraguard](https://github.com/DarkGhostHunter/Laraguard), available that can accomplish the goal of providing a solution that does not require dependency on a 3rd-party authenticator like Microsoft or Google.

This package provides the benefit of being portable, meaning it _**"silently enables authentication using 6 digits codes, without Internet or external providers"**_.
### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
Will be a post stable feature.
