### ISSUE TITLE
Installation not running, undefined variable host!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [fusioncms/fusioncms#484]
### Describe the issue
(FusionCMS/CMS) package installed successfully on a fresh laravel 7 installtion 
but **php artisan fusion:install** not working.

### To reproduce
Install a fresh laravel 7, then run **composer require fusioncms/cms**
Then try to run php artisan fusion:install then you will get: **Undefined variable host**!

### Expected behavior
To work just fine.

### Screenshots
![Fhost_sc](https://user-images.githubusercontent.com/5323832/80665143-f519eb00-8a98-11ea-9fd7-771802a10e51.png)

### Version and browser
**PHP** 7.2.27
**Laravel** 7.9
Fusion **CMS** Package (Latest)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by skrolikowski** [comment]
Taking a look.
In the meantime there are some undocumented options that may fit your needs.

### Installation for a Homestead setup
`php artisan fusion:install --homested`

#### Defaults
- `url`              = "http://localhost"
- `host`           = "localhost"
- `database`   = "fusioncms"
- `username`  = "homestead"
- `password`   = "secret"
- `charset`       = "utf8"
- `collation`     = "utf8_unicode_ci"

### Installation for a Valet setup
`php artisan fusion:install --valet`

#### Defaults
- `url`              = "http://localhost"
- `host`           = "localhost"
- `database`   = "fusioncms"
- `username`  = "root"
- `password`   = ""
- `charset`       = "utf8"
- `collation`     = "utf8_unicode_ci"

**Comment by Mu9tafa-Online** [comment]
So what should i change, I'm using Laragon. How to make the installation command work?

**Comment by kaidesu** [comment]
Bug on our end :v: we just merged in https://github.com/fusioncms/cms/pull/14 which fixes the `$host` variable missing - you'll want to utilize the `--database`, `--password`, and `--username` flags in the mean time:

```
php artisan fusion:install --database="my_website" --username="root" --password="secret"
```

We will be adding the full installation wizard back in in a separate PR shortly that will walk you through all these required steps.

Sorry for the inconvenience!
