### ISSUE TITLE
Activity log breaks when a referenced resource is deleted

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#493]
### Describe the issue
When a resource that is listed in the activity panel is deleted, it prevents the activity panel from displaying any information at all. You will find a 500 error from the API in relation to this. 

### To reproduce
- Create a matrix
- Delete the matrix
- Navigate to the dashboard and see that the activity log is empty

### Expected behavior
The reference to the "relationship" to be cleared within the activity panel. We are using Spatie's [laravel-activitylog](https://docs.spatie.be/laravel-activitylog/v3/introduction/) package for this functionality, so maybe there's something to handle this situation already?

### Screenshots
![Screen Shot 2020-05-01 at 3 40 22 PM](https://user-images.githubusercontent.com/355659/80846733-1c200c00-8bc2-11ea-915e-f75a0c41b3cb.png)

### Version and browser
Version: Beta 5

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by thekanbo** [comment]
@kaidesu This was something we had worked on previously (https://github.com/fusioncms/fusioncms/pull/92/files); had to do with the activity log trying to load a model file that no longer existed. Maybe something we changed since then is causing it to come back up?

**Comment by kaidesu** [comment]
It's possible - we'll want to get this covered by a unit test or two to ensure it stays unbroken 🤘

**Comment by skrolikowski** [comment]
> We are using Spatie's laravel-activitylog package for this functionality, so maybe there's something to handle this situation already?

Spatie says [no](https://github.com/spatie/laravel-activitylog/issues/353).
