### ISSUE TITLE
theme_path() helper returns Class import error

### ISSUE THREAD

**Issue by manda-ikaink** [fusioncms/fusioncms#505]
### Describe the issue
Currently unable to utilize the `theme_path()` helper in my theme as it returns an error related to missing class import.

### Screenshots
<img width="1242" alt="Screen Shot 2020-05-12 at 11 28 36 AM" src="https://user-images.githubusercontent.com/5963302/81731577-fad1e200-9443-11ea-9bac-c7a2166585de.png">

### Version and browser
Version: Master

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
Will be an update to the caffeinated package to fix this~
