### ISSUE TITLE
Creating a menu generates slug with a dash instead of underscore

### ISSUE THREAD

**Issue by manda-ikaink** [fusioncms/fusioncms#512]
### Describe the issue
When creating a Menu, the slug generated replaces spacing with a dash instead of the expected underscore. This causes a number of other issues once the menu has been created, including the inability to edit the menu or add menu items.

If I manually format the handle correctly, when I go to edit the Menu it will revert the handle back to the original dash vs underscore format. It seems once the Menu has been saved it should not attempt to re-format the handle. 

### Screenshots
<img width="1267" alt="Screen Shot 2020-05-14 at 11 00 18 AM" src="https://user-images.githubusercontent.com/5963302/81969270-84afb580-95d2-11ea-95e4-ae0a172bc9d1.png">

### Version and browser
Version: Master

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by skrolikowski** [comment]
This was resolved in PR [28](https://github.com/fusioncms/cms/pull/28).
