### ISSUE TITLE
Feature request: Add "children" and "parent" to list of reserved keywords

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#518]
### Is your feature request related to a problem? Please describe.
`children` and `parent` are common keys added to collections that support parent/child relationships. These should be added to our reserved keyword ruleset.

### Additional context
This cropped up when creating a navigation menu with an assigned fieldset that had a "children" field created. Once it was set, the control panel would throw a 500 error due to the fieldset `children` field taking precedence.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by skrolikowski** [comment]
The `NotAReservedKeyword` rule was created for the Matrix modules that are required to generate a table (we may need to change the name).

However this request is for different issue (e.g. conflicting field names with user-defined variable names 'parent' & 'children'). An alternative suggestion would be to namespace these values like so:

```php
$resource['related']   = [
    'parent' => new NodeResource($this->parent),
    'children' => NodeResource::collection($this->children)
];
```
