### ISSUE TITLE
The mix manifest does not exist!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [fusioncms/fusioncms#542]
### Describe the issue
I see "The Mix manifest does not exist" error when try to access admin url on a fresh installtion.

### To reproduce
Install a fresh FusionCMS (beta 6) and visit admin url

### Expected behavior
To work just fine.

### Screenshots
![erro_fus](https://user-images.githubusercontent.com/5323832/83516385-3f96e900-a4d7-11ea-93c7-8b6bcedeac8e.PNG)

### Version and browser
**FusionCMS**: v6.0 Beta 6
**PHP**:  7.2.27
**Browser**: Chrome (Latest)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
Hmm, so far I've been unable to reproduce this locally. Wonder if it has something to do with running on Windows vs. *Nix.

Also, how did you grab the latest copy of FusionCMS? GitHub clone, download, or through the CLI?

**Comment by Mu9tafa-Online** [comment]
I downloaded it from GitHub releases page.

**Comment by Mu9tafa-Online** [comment]
I installed it again and the error is gone.
