### ISSUE TITLE
Issue: Cannot declare class CreateUsersTable!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [fusioncms/fusioncms#555]
### Describe the issue
I download a fresh copy of fusionCMS beta 6 from github and when installing a  i get this error:
**Whoops\Exception\ErrorException**: 
Cannot declare class CreateUsersTable, because the name is already in use

### To reproduce
Get a fresh copy of the fusionCMS beta 6 and install it.

### Expected behavior
To install successfully.

### What I did to fix it?
I deleted the default laravel users migraion "**2014_10_12_000000_create_users_table**" ,, and the error is gone!

### Screenshots
![fus_users](https://user-images.githubusercontent.com/5323832/83852504-2f1f8200-a714-11ea-9b47-cceea33ba47d.PNG)

### Version and browser
FusionCMS: v6.0 Beta 6
PHP: 7.2.27
Browser: Chrome (Latest)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by mustafa-online** [comment]
@kaidesu This is still not fixed :(

**Comment by skrolikowski** [comment]
@Mu9tafa-Online It's possible this is related to your autoload file generated by composer. Check out this [issue](https://github.com/laravel/framework/issues/8782).

You could also try running: `composer dump-autoload`

**Comment by mustafa-online** [comment]
@skrolikowski  I tried dump-autoload but it's still triggering the error, i fixed it by removing the users migration file / or change it's name.

I think we can close this for now.
