### ISSUE TITLE
Minor UI Tweaks

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#623]
This issue will collect a list of minor UI tweaks to be made vs. opening issues for each item. Once an issue has been resolved we'll update this issue and link to the related PR.

---

- [x] Fieldset select component not rendering (fusioncms/cms#127)
- [x] Numerous error messages related to toggle component (fusioncms/cms#127)

**Comment by K-E-L** [comment]
closing, all tasks done
