### ISSUE TITLE
Feature request: Gutenberg editor as a field type!

### ISSUE THREAD

**Issue by mustafa-online** [fusioncms/fusioncms#632]
### Is your feature request related to a problem? Please describe.
Add gutenberg editor (field type) to allow more content control.

### Describe the solution you'd like
to have a Gutenberg field as option when creating content (as a replacement for ckeditor or tinymce).
you can check this repo: [Laraberg](https://github.com/VanOns/laraberg)

### Additional context (screenshot for gutenberg )
![laraberg-1](https://user-images.githubusercontent.com/5323832/90392854-f4c94e00-e08f-11ea-8002-9827a697c39b.png)

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
We'll be exploring block-type editors in the future :v:
