### ISSUE TITLE
Exception thrown after spatie/laravel-permission update

### ISSUE THREAD

**Issue by huiyang** [fusioncms/fusioncms#637]
### Describe the issue
Exception thrown:
Declaration of Fusion\Models\Role::users(): Illuminate\Database\Eloquent\Relations\MorphToMany must be compatible with Spatie\Permission\Models\Role::users(): Illuminate\Database\Eloquent\Relations\BelongsToMany

Caused by spatie/laravel-permission update:
https://github.com/spatie/laravel-permission/commit/95fb0a69b862e812f7cc1ceafc2d6a78390c72d8#diff-d99643c10f202087a943d4258b7e3626

### To reproduce
Update spatie/laravel-permission to latest version (eg: 3.16.0)

### Expected behavior
No exception thrown

### Screenshots
![image](https://user-images.githubusercontent.com/517651/90948980-b6100b00-e476-11ea-9560-efb41977715c.png)

### Version and browser
Version: v6.0.0-beta.10
Browser and version: Not applicable

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate
- [x] I have detailed how the issue can be reproduced

**Comment by mustafa-online** [comment]
Yes, I can confirm this. I've just tried a fresh installation.

**Comment by cam-vanorman** [comment]
Adding to this issue as I'm also able to confirm the following error when attempting to install the CMS on the CLI:

```php
Declaration of Fusion\Models\Permission::users(): Illuminate\Database\Eloquent\Relations\MorphToMany must be compatible with Spatie\Permission\Models\Permission::users(): Illuminate\Database\Eloquent\Relations\BelongsToMany
```

![Screen Shot 2020-10-13 at 10 35 09 AM](https://user-images.githubusercontent.com/5124234/95896228-c76fe800-0d40-11eb-97cc-be6e7be264c0.png)

**Information added to install process:**

```
Application name:      Fusion CMS
Application URL:       http://localhost
Database host:         localhost
Database name:         fusioncms
Database username:     homestead
Database password:     secret
Database charset:      utf8
Database collation:    utf8_general_ci
Default user name:     Lise Meitner
Default user email:    admin@example.com
Default user password: secret
```

**Comment by kaidesu** [comment]
@cam-vanorman can you download the latest version and verify that this has been resolved? We've pushed a lot of updates to the user system recently.

**Comment by cam-vanorman** [comment]
@kaidesu 

![ohyeahsure](https://user-images.githubusercontent.com/5124234/96309153-98b07680-0fb9-11eb-91b9-e8e38bb2a67d.gif)

**Comment by cam-vanorman** [comment]
@kaidesu, Tested with the latest changes on a fresh install and it appears to be installing just fine. 

<img width="476" alt="Screen Shot 2020-10-16 at 8 55 07 PM" src="https://user-images.githubusercontent.com/5124234/96327809-e2b54e80-0ff1-11eb-9b34-2ea35e78e27d.png">
