### ISSUE TITLE
Remove Extensions

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#649]
The extensions API is no longer needed with the upcoming blueprint update. Any addons that wish to extend and make use of the blueprint system to extend its content offerings will be able to generate and utilize blueprints just like the core systems do.

**Comment by huiyang** [comment]
How should we bind fields/fieldset/blueprint to a a eloquent model after extensions has been removed? 
I can't bind blueprint to model as I don't have the value "blueprinttable_id".

Anyone can give some hint? Thanks.
