### ISSUE TITLE
Slug with utf encoding character such as Chinese is not supported

### ISSUE THREAD

**Issue by huiyang** [fusioncms/fusioncms#660]
### Describe the issue
Slug with utf encoding character such as Chinese is not supported.

### To reproduce
Create a new collection, type chinese character (eg: 中文) in title, slug is empty with a single dash

### Expected behavior
Slug is same as title

### Screenshots
![image](https://user-images.githubusercontent.com/517651/93457662-dd40e780-f911-11ea-9b82-7e517500de26.png)

### Version and browser
Version: 6.0.0-beta.10
Browser and version: Google chrome v85

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by huiyang** [comment]
I replaced this 
``` javascript
.replace(/([^\w\s]|_)+/g, ' ')           // Remove all non-word chars
```
with
``` javascript
.replace(/(\p{S}|\p{P}|\s)+/gu, ' ')       // Remove all symbols
```
in fusioncms\cms\resources\js\ui\Slug\Slug.vue
and it seem working now

**Comment by kaidesu** [comment]
Got this merged in, thanks @huiyang! You're the real MVP~
