### ISSUE TITLE
Feature request: Video Fieldtype - Preview Update

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#697]
### Is your feature request related to a problem? Please describe.
The Preview for the Video Fieldtype does not support external URL (i.e. Youtube).

### Related issues:
- #564 
- #695 

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
We use **Plyr** in the file manager for video (and technically, audio) previews - it also supports youtube/vimeo URLs directly.

https://plyr.io/
