### ISSUE TITLE
Matrix overview interfaces

### ISSUE THREAD

**Issue by kaidesu** [fusioncms/fusioncms#701]
### Is your feature request related to a problem? Please describe.
The entry point into a matrix should be an overview/dashboard of the content and stats.

### Describe the solution you'd like
...

### Describe alternatives you've considered
...

### Additional context
...

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#271 and fusioncms/cms#266
