### ISSUE TITLE
New Folder -> Delete Confirmation?

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#719]
### Describe the issue
Within the File Manager we're experiencing some unexpected behavior. See screenshot section for more info.

### To reproduce
Unable to reproduce 100% of the time at the moment.

### Screenshots
![](https://cdn.discordapp.com/attachments/333785237156790284/804416893267083324/issue.gif)

### Version and browser
Version: Give us the version of FusionCMS here
Browser and version: If applicable give us your browser specs

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closing, unable to replicate
