### ISSUE TITLE
Define New/Existing Field.

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#720]
### Describe the issue
When editing a **Structure** (e.g. Matrix, Taxonomy, Form) and adding a new Field the Modal will act like you're editing an existing field.

### Expected behavior
- Adding a field => Label as New Field; Allow handle auto-updates.
- Editing a field => Label as Edit Field; Disable handle auto-updates.

### Screenshots
<img width="898" alt="Screen Shot 2021-01-29 at 11 02 59 AM" src="https://user-images.githubusercontent.com/8143970/106316739-0d828600-6222-11eb-9f86-8302c9cf8998.png">

### Version and browser
Version: v6.0.0.beta-10
Browser and version: Chrome (latest)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#366
