### ISSUE TITLE
Feature request: Update system ordering to use floats

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#732]
### Is your feature request related to a problem? Please describe.
[Navigation Refactor](https://github.com/fusioncms/cms/pull/316) introduces a new, efficient method of ordering that uses floats instead of integers. This allows for easily reordering items without having to update multiple rows. We'd like to integrate this into the other components.

### Describe the solution you'd like
Update method of sorting to match that of **Navigation**.

### Additional context
[Reference](https://codecourse.com/courses/flexible-database-ordering-with-laravel)

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#382 and fusioncms/cms#381
