### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by yanielbf** [fusioncms/fusioncms#746]
Hi, I was trying to upload an image to the filemanager but I couldn't. the error listed was that the type of file you were uploading was wrong. I checked the settings and I had added the allowed extensions and then I went to debug the code internally. You can detect that in the file `resources/js/components/FileManager/FileUploader.vue` on lines 92 and 93 the key files.accepted_files and files.file_size_upload_limit are used to fetch data from Vuex. These keys do not exist as they are created in settings.js they do not have the prefix "files.". Also rectify and in the `src/Http/Requests/FileUploadRequest.php` line 50 an attempt is made to implode a collection so it gives an error. If this is not correct Excuse the corrections and if you can tell me how to solve the problem of uploading the images using this form

**Comment by K-E-L** [comment]
Closing, I am able to upload images such as gif, png, jpg, and svg. Also, the files `resources/js/components/FileManager/FileUploader.vue` and `src/Http/Requests/FileUploadRequest.php` no longer exist.
