### ISSUE TITLE
Feature request: Disable user registration by default

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#753]
### Is your feature request related to a problem? Please describe.
When installing a new site, the public user registration is enabled by default.

### Describe the solution you'd like
Public user registration is less likely to be needed, so registration should default to disabled.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#371
