### ISSUE TITLE
Matrix helpers not working

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#754]
### Describe the issue
The helpers `matrix_page()` and `matrix_entries()` do not return data, and display a 500 error. It appears that the `Single` and `Collection` builder services no longer exist. 

```
Class 'Fusion\Services\Builders\Single' not found (View: /home/vagrant/Code/myproject/themes/Mytheme/resources/views/layouts/default.blade.php)
```

### To reproduce
Create a new matrix (collection or single), and try and return data with `matrix_page()` and `matrix_entries()`.

### Expected behavior
Model data or collections should be returned

### Screenshots
![image](https://user-images.githubusercontent.com/7810450/113759649-2bf57980-96ca-11eb-85a3-3bd5779b37cc.png)

### Version and browser
Nightly

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#391
