### ISSUE TITLE
Feature request: Manual entry ordering

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#755]
### Describe the solution you'd like
Add ability to manually sort entries in a matrix collection

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#381
