### ISSUE TITLE
I am getting 419 no metter what

### ISSUE THREAD

**Issue by safarovitch** [fusioncms/fusioncms#757]
### Describe the issue
Installed the cms as described in documentation. Instead of homstead I am using wamp server to develop locally and so far I have no issues developing with laravel. Today I wanted to install fusioncms and experiment with it. I came accross with several problems for instance I am using Mysql server without password and eventually had to make some changes to get fusioncms up and running. After installation no metter what I do it always throws 419 error when registering or logging in.

### Version and browser
Version: 6.0.0-beta.9
Browser and version: Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)

### Bug report checklist
- [check ] I have filled out as much information as I can
- [check  ] I have detailed how the issue can be reproduced
- [check  ] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by huiyang** [comment]
Please use virtual host to access the web site, eg: `http://xxxx.local` or `http://xxxx.dev`,
also, please make sure there is no port number in your virtual host (mean must use port 80).

❌http://fusioncms.local:8080/admin
❌http://fusioncms.local/cms/admin
❌http://localhost/admin
❌http://localhost/fusioncms/admin

✔http://fusioncms.local/admin
✔http://fusion.dev/admin

If still have the same 419 error, please try to clear cookie or open the web site in incognito mode to check if it work or not?

**Comment by huiyang** [comment]
By the way, I just found that if `APP_URL` is not set correctly, eg: your url should be http://fusion.local but `APP_URL` is set to http://localhost, then it will caused 401 error.

**Comment by K-E-L** [comment]
closed
