### ISSUE TITLE
Stop Installation on MySQL page

### ISSUE THREAD

**Issue by aliqasemzadeh** [fusioncms/fusioncms#759]
Hi
When I want to install FCMS in mysql setup page i get no error and it stop installation there.

**Comment by huiyang** [comment]
Please mention which version you are using and follow/use the bug reporting format/template.

**Comment by aliqasemzadeh** [comment]
@huiyang 
6.0.0 Beta 10

**Comment by huiyang** [comment]
The bug is caused by wrong name of the input field, please refer to this to debug:
https://github.com/antwebstudio/fusion-cms/commit/32db27259c535e10e662812e091774fb94286924

**Comment by aliqasemzadeh** [comment]
@huiyang 
How can i fix it?

**Comment by huiyang** [comment]
I have already show you in my previous reply.

**Comment by aliqasemzadeh** [comment]
@huiyang 
Please make pull request and accept it.

**Comment by huiyang** [comment]
No, since it is a outdated version.
You may use my forked version or fork yourself another repo to make changes.

**Comment by aliqasemzadeh** [comment]
@huiyang Please give me link.

**Comment by huiyang** [comment]
I already gave you in previous comment....

**Comment by K-E-L** [comment]
closed by fusioncms/cms#226
