### ISSUE TITLE
Feature request: Send Test Email

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#760]
### Is your feature request related to a problem? Please describe.
Currently, there is no way to test and confirm email settings after entering them in the control panel.

### Describe the solution you'd like
There should be a button to send a test email from the system to an email address of choice.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#402
