### ISSUE TITLE
Feature request: Visually distinguish fields and fieldsets in blueprint building

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#761]
### Is your feature request related to a problem? Please describe.
Fieldsets can be created independent of any existing matrices or blueprints. When building the blueprint/when adding fields to that model, it is not immediately obvious that a fieldset can be added.

![image](https://user-images.githubusercontent.com/7810450/133863242-ebc07d9b-d26f-4502-90d4-6276233a3ca3.png)

### Describe the solution you'd like
Instead of listing "Fieldset" alongside the rest of the fieldtypes, it should be in its own section or line.

### Feature request checklist
- [x] This is a single feature (i.e. not a re-write of the entire CMS)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: add konami code to control panel`)
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#367
