### ISSUE TITLE
Handle doesn't auto-populate when adding/editing a field

### ISSUE THREAD

**Issue by thekanbo** [fusioncms/fusioncms#762]
### Describe the issue
When adding or editing a field, the `handle` does not update when changing the `name`:

![image](https://user-images.githubusercontent.com/7810450/133863416-16535ed8-511e-4a0b-bb51-07c15de4faf3.png)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by K-E-L** [comment]
closed by fusioncms/cms#365
